# Generated by Django 4.2.7 on 2023-11-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Rating Date')),
                ('ranking', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Average'), ('D', 'Poor')], default='A', max_length=1)),
                ('movieposter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movieposter')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
