# Generated by Django 4.2.7 on 2023-11-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_actors_remove_movieposter_actors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.AddField(
            model_name='movieposter',
            name='actors',
            field=models.ManyToManyField(to='main_app.actor'),
        ),
    ]
